# Generated by Django 5.0.4 on 2025-06-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('Slug', models.CharField(max_length=200)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
