# Generated by Django 5.0.4 on 2025-06-29 12:03

from django.db import migrations, models
import django_quill.fields   # ✅ Use Quill

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_time_blog_time_blog_image_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Category',
            field=models.CharField(
                choices=[
                    ('politics', 'Politics'),
                    ('sports', 'Sports'),
                    ('education', 'Education'),
                    ('culture', 'Culture')
                ],
                default='politics',
                max_length=50
            ),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=django_quill.fields.QuillField(),   # ✅ Use QuillField
        ),
        migrations.AlterField(
            model_name='blog',
            name='Slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
