# Generated by Django 5.0.4 on 2025-06-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='time',
            new_name='submitted_at',
        ),
    ]
