# Generated by Django 5.0.4 on 2025-11-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_time_contactmessage_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='event_place',
            field=models.CharField(blank=True, help_text='Optional event venue or location.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='event_time',
            field=models.DateTimeField(blank=True, help_text='Optional event time for political/sports/culture events.', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='overlay_text',
            field=models.CharField(blank=True, help_text='Text displayed over the blog image.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short text shown on cards and previews.', null=True),
        ),
    ]
