# Generated by Django 5.0.4 on 2025-11-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_dailyvisitor_blog_event_place_blog_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('politics', 'Politics'), ('sports', 'Sports'), ('education', 'Education'), ('culture', 'Culture'), ('economics', 'Economics')], default='politics', max_length=50),
        ),
    ]
