# Generated by Django 5.0.4 on 2025-12-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_user_alter_blog_event_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='adverts/')),
                ('code', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('position', models.CharField(choices=[('header', 'Header'), ('sidebar', 'Sidebar'), ('inpost', 'In-Post'), ('footer', 'Footer')], default='sidebar', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Support Us', max_length=255)),
                ('mpesa_paybill', models.CharField(blank=True, max_length=50, null=True)),
                ('mpesa_account', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('sponsor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate_link', models.URLField(blank=True, null=True)),
                ('affiliate_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_until', models.DateField(blank=True, null=True)),
                ('show_ads', models.BooleanField(default=True)),
                ('is_paid_review', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
