# Generated by Django 5.0.4 on 2025-12-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_advert_category_donationinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='submitted_at',
            new_name='time',
        ),
    ]
