# Generated by Django 6.0 on 2025-12-15 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_submitted_at_contactmessage_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='affiliate_images/')),
                ('active', models.BooleanField(default=True)),
                ('position', models.CharField(blank=True, help_text='Optional position for template placement (e.g., sidebar, footer, inpost)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='featured_posts/')),
                ('active', models.BooleanField(default=True)),
                ('position', models.CharField(blank=True, help_text='Optional position for template placement (e.g., sidebar, footer, inpost)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_featured_posts', to='blog.blog')),
            ],
        ),
        migrations.DeleteModel(
            name='Advert',
        ),
        migrations.DeleteModel(
            name='DonationInfo',
        ),
    ]
